//! Templates — render a `ContractDoc` to Markdown or HTML.

use crate::parser::{ContractDoc, FunctionDoc};

/// Render to Markdown.
pub fn render_markdown(doc: &ContractDoc) -> String {
    let mut out = String::new();

    out.push_str(&format!("# {} — API Reference\n\n", doc.contract));
    out.push_str("> Auto-generated by `tipjar-doc-generator`. Do not edit manually.\n\n");

    // Error table
    if !doc.errors.is_empty() {
        out.push_str("## Error Codes\n\n");
        out.push_str("| Code | Name |\n|------|------|\n");
        for e in &doc.errors {
            out.push_str(&format!("| `{}` | `{}` |\n", e.code, e.name));
        }
        out.push('\n');
    }

    out.push_str("## Functions\n\n");
    for f in &doc.functions {
        out.push_str(&render_function_md(f));
    }

    out
}

fn render_function_md(f: &FunctionDoc) -> String {
    let mut out = String::new();
    out.push_str(&format!("### `{}`\n\n", f.name));

    if !f.doc.is_empty() {
        out.push_str(&format!("{}\n\n", f.doc));
    }

    // Signature
    let params_sig = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "```rust\npub fn {}({}) -> {}\n```\n\n",
        f.name, params_sig, f.returns
    ));

    // Parameters table
    if !f.params.is_empty() {
        out.push_str("**Parameters**\n\n");
        out.push_str("| Name | Type |\n|------|------|\n");
        for p in &f.params {
            out.push_str(&format!("| `{}` | `{}` |\n", p.name, p.ty));
        }
        out.push('\n');
    }

    // Returns
    if f.returns != "()" {
        out.push_str(&format!("**Returns** — `{}`\n\n", f.returns));
    }

    // Example
    out.push_str(&format!("{}\n\n---\n\n", render_example(f)));

    out
}

fn render_example(f: &FunctionDoc) -> String {
    let args = f
        .params
        .iter()
        .map(|p| format!("&{}", p.name))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "**Example**\n\n```rust\nclient.{}({});\n```",
        f.name, args
    )
}

/// Render to a self-contained HTML page with basic search.
pub fn render_html(doc: &ContractDoc) -> String {
    let mut functions_html = String::new();
    let mut nav_items = String::new();

    for f in &doc.functions {
        nav_items.push_str(&format!(
            "<li><a href=\"#fn-{}\">{}</a></li>\n",
            f.name, f.name
        ));
        functions_html.push_str(&render_function_html(f));
    }

    let errors_html = if doc.errors.is_empty() {
        String::new()
    } else {
        let rows = doc
            .errors
            .iter()
            .map(|e| format!("<tr><td><code>{}</code></td><td><code>{}</code></td></tr>", e.code, e.name))
            .collect::<Vec<_>>()
            .join("\n");
        format!(
            "<section id=\"errors\"><h2>Error Codes</h2>\
             <table><thead><tr><th>Code</th><th>Name</th></tr></thead>\
             <tbody>{rows}</tbody></table></section>"
        )
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{contract} API</title>
<style>
  body{{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#222}}
  h1{{border-bottom:2px solid #0070f3;padding-bottom:.5rem}}
  h2{{color:#0070f3}}
  h3{{font-family:monospace;background:#f4f4f4;padding:.4rem .8rem;border-radius:4px}}
  pre{{background:#f4f4f4;padding:1rem;border-radius:4px;overflow-x:auto}}
  code{{font-family:monospace;background:#f4f4f4;padding:.1rem .3rem;border-radius:3px}}
  table{{border-collapse:collapse;width:100%}}
  th,td{{border:1px solid #ddd;padding:.5rem .8rem;text-align:left}}
  th{{background:#f0f0f0}}
  nav ul{{list-style:none;padding:0;display:flex;flex-wrap:wrap;gap:.5rem}}
  nav a{{text-decoration:none;color:#0070f3;border:1px solid #0070f3;padding:.2rem .6rem;border-radius:4px}}
  #search{{width:100%;padding:.5rem;font-size:1rem;margin-bottom:1rem;border:1px solid #ccc;border-radius:4px}}
  .fn-section{{border-bottom:1px solid #eee;padding-bottom:1.5rem;margin-bottom:1.5rem}}
  .hidden{{display:none}}
  .note{{color:#666;font-style:italic;font-size:.9rem}}
</style>
</head>
<body>
<h1>{contract} — API Reference</h1>
<p class="note">Auto-generated by <code>tipjar-doc-generator</code>. Do not edit manually.</p>
<input id="search" type="search" placeholder="Search functions…" oninput="filterFns(this.value)">
<nav><ul>{nav_items}</ul></nav>
{errors_html}
<h2>Functions</h2>
{functions_html}
<script>
function filterFns(q){{
  q=q.toLowerCase();
  document.querySelectorAll('.fn-section').forEach(s=>{{
    s.classList.toggle('hidden',q&&!s.id.includes(q)&&!s.textContent.toLowerCase().includes(q));
  }});
}}
</script>
</body>
</html>"#,
        contract = doc.contract,
        nav_items = nav_items,
        errors_html = errors_html,
        functions_html = functions_html,
    )
}

fn render_function_html(f: &FunctionDoc) -> String {
    let params_sig = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty))
        .collect::<Vec<_>>()
        .join(", ");

    let doc_html = if f.doc.is_empty() {
        String::new()
    } else {
        format!("<p>{}</p>", f.doc.replace('\n', "<br>"))
    };

    let params_html = if f.params.is_empty() {
        String::new()
    } else {
        let rows = f
            .params
            .iter()
            .map(|p| format!("<tr><td><code>{}</code></td><td><code>{}</code></td></tr>", p.name, p.ty))
            .collect::<Vec<_>>()
            .join("\n");
        format!(
            "<h4>Parameters</h4><table><thead><tr><th>Name</th><th>Type</th></tr></thead>\
             <tbody>{rows}</tbody></table>"
        )
    };

    let returns_html = if f.returns == "()" {
        String::new()
    } else {
        format!("<p><strong>Returns</strong> — <code>{}</code></p>", f.returns)
    };

    let example_args = f
        .params
        .iter()
        .map(|p| format!("&amp;{}", p.name))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"<section class="fn-section" id="fn-{name}">
<h3>{name}</h3>
{doc_html}
<pre><code>pub fn {name}({sig}) -&gt; {ret}</code></pre>
{params_html}
{returns_html}
<h4>Example</h4>
<pre><code>client.{name}({example_args});</code></pre>
</section>
"#,
        name = f.name,
        sig = params_sig,
        ret = f.returns,
        doc_html = doc_html,
        params_html = params_html,
        returns_html = returns_html,
        example_args = example_args,
    )
}
